server:
  port: 8081


security:
  jwt:
    exp-time: 1800000
    secret-key: "01d086773f9e6a974916251d90051c9141b8834a6ebc05680fa8545edd625d5e"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_info
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: ORDER-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka










