server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_info
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

#    properties:
#      hibernate.transaction.jta.platform: com.atomikos.icatch.jta.hibernate4.AtomikosPlatform
  application:
    name: PRODUCT-SERVICE


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/



